name: Deploy React App
on: [workflow_dispatch, push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run tests in app
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint app src
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Deploy
        run: echo Deploying...