name: Deploy React App!
on:
  push:
    branches:
      - 'main'
#    paths-ignore:
#      - '.github/workflows/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Run tests in app
        run: npm run test
      - name: Lint app src
        run: npm run lint
      - name: Build app
        run: npm run build
      - name: Deploy
        run: echo Deploying...

      - name: Copy single file to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: your-artifact
          remote: remote-path/your-artifact
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}